
### to setup services ###


services:
  db:
    image: public.ecr.aws/docker/library/mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: StreetSuite123456
      MYSQL_DATABASE: streetsuite_db
      MYSQL_USER: StreetSuite
      MYSQL_PASSWORD: StreetSuite123456
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  djangoserver:
    container_name: streetsuite-backend
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    env_file:
      - .env

  redis:
    image: public.ecr.aws/docker/library/redis:latest
    container_name: redis

    
  celery_5mins:
    container_name: celery_5mins
    build: .
    command: celery -A Streetsuite.celery worker -Q celery_5mins -l info
    restart: always
    depends_on:
      - redis
    env_file:
      - .env

  # celery_1hour:
  #   container_name: celery_1hour
  #   build: .
  #   command: celery -A Streetsuite.celery worker -Q celery_1hour -l info
  #   restart: always
  #   depends_on:
  #     - redis
  #   env_file:
  #     - .env
  
  # celery_4hour:
  #   container_name: celery_4hour
  #   build: .
  #   command: celery -A Streetsuite.celery worker -Q celery_4hour  -l info
  #   restart: always
  #   depends_on:
  #     - redis
  #   env_file:
  #     - .env

  # celery_1day:
  #   container_name: celery_1day
  #   build: .
  #   command: celery -A Streetsuite.celery worker -Q celery_1day  -l info
  #   restart: always
  #   depends_on:
  #     - redis
  #   env_file:
  #     - .env
  
  # celery_twitter:
  #   container_name: celery_twitter
  #   build: .
  #   command: celery -A Streetsuite.celery worker -Q Twitter --pool=solo -l info
    
  #   restart: always
  #   depends_on:
  #     - redis
  #   env_file:
  #     - .env

  celery-beat:
    container_name: celery-beat
    build: .
    command: celery -A Streetsuite beat -l info 
    restart: always
    depends_on:
      - redis
      # - celery
      # - celery_timeless
      - celery_5mins
      # - celery_1hour
      # - celery_4hour
      # - celery_1day
      # - celery_twitter
    env_file:
      - .env

volumes:
  db_data:

  # db:
  #   image: mysql
  #   environment:
  #    - DB_HOST: 54.39.103.222
  #    - DB_PORT: 3306
  #    - DB_USER: streetsuite_db
  #    - DB_PASS: z!AN0ZC0M@)z
  #    - DB_NAME: streetsuite_db
  #   volumes:
  #     -
