### to setup services ###


services:
  db:
    image: public.ecr.aws/docker/library/mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: z!AN0ZC0M@)z
      MYSQL_DATABASE: streetsuite_db
      MYSQL_USER: streetsuite_db
      MYSQL_PASSWORD: z!AN0ZC0M@)z
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  djangoserver:
    container_name: streetsuite-backend
    build: .
    command: python manage.py runserver 0.0.0.0:80
    ports:
      - "80:80"
    volumes:
      - .:/app
    depends_on:
      - db
    env_file:
      - .env

  redis:
    image: public.ecr.aws/docker/library/redis:latest
    container_name: redis

  celery:
    container_name: celery
    build: .
    command: celery -A Streetsuite.celery worker --pool=solo -l info
    
    restart: always
    depends_on:
      - redis
    env_file:
      - .env

  celery-beat:
    container_name: celery-beat
    build: .
    command: celery -A Streetsuite beat -l info 
    restart: always
    depends_on:
      - redis
      - celery
    env_file:
      - .env

volumes:
  db_data:

  # db:
  #   image: mysql
  #   environment:
  #    - DB_HOST: 54.39.103.222
  #    - DB_PORT: 3306
  #    - DB_USER: streetsuite_db
  #    - DB_PASS: z!AN0ZC0M@)z
  #    - DB_NAME: streetsuite_db
  #   volumes:
  #     -


