# Generated by Django 5.0.6 on 2024-08-04 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='passed',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='useremail',
            name='quiz',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='QuizApp.subcategory'),
            preserve_default=False,
        ),
    ]
