# Generated by Django 5.0.6 on 2024-08-04 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0002_subcategory_passed_useremail_quiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useremail',
            name='quiz',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='users',
            field=models.ManyToManyField(to='QuizApp.useremail'),
        ),
    ]
