# Generated by Django 5.0.6 on 2024-06-09 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0004_alter_quizzes_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizzes',
            name='duration',
        ),
    ]
