# Generated by Django 5.0.6 on 2024-06-09 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0005_remove_quizzes_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizzes',
            name='category',
        ),
        migrations.AddField(
            model_name='quizzes',
            name='categories',
            field=models.ManyToManyField(to='QuizApp.category'),
        ),
    ]
