# Generated by Django 5.0.6 on 2024-06-09 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0006_remove_quizzes_category_quizzes_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='quizzes',
            options={'ordering': ['id']},
        ),
    ]
