# Generated by Django 5.0.6 on 2024-11-12 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0006_alter_subcategory_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='duration',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='users',
            field=models.ManyToManyField(to='QuizApp.useremail'),
        ),
    ]
