# Generated by Django 5.0.6 on 2024-06-09 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0007_alter_answer_options_alter_quizzes_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizzes',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
