# Generated by Django 5.0.6 on 2024-11-13 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0007_alter_subcategory_duration_alter_subcategory_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='users',
        ),
    ]
