# Generated by Django 5.0.6 on 2024-06-10 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0008_quizzes_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizzes',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizzes',
            name='score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
