# Generated by Django 5.0.6 on 2024-11-13 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0008_remove_subcategory_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='users',
            field=models.ManyToManyField(blank=True, to='QuizApp.useremail'),
        ),
    ]
