# Generated by Django 5.0.6 on 2024-06-10 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0010_quizzes_achievement_quizzes_enrollers_quizzes_likes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizzes',
            name='categories',
        ),
        migrations.AddField(
            model_name='category',
            name='quizzes',
            field=models.ManyToManyField(to='QuizApp.quizzes'),
        ),
    ]
