# Generated by Django 5.0.6 on 2024-06-10 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0011_remove_quizzes_categories_category_quizzes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='text',
        ),
    ]
