# Generated by Django 5.0.6 on 2024-06-10 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0012_rename_name_category_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='text',
            new_name='name',
        ),
    ]
