# Generated by Django 5.0.6 on 2024-05-27 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0009_post_description_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='contentimage',
            field=models.ImageField(default='', upload_to='PostPic/'),
        ),
        migrations.AddField(
            model_name='post',
            name='time_reading',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='videolink',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='', upload_to='CoverPic/'),
        ),
    ]
