# Generated by Django 5.0.6 on 2024-05-27 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0011_remove_post_image_alter_post_contentimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time_reading',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
