# Generated by Django 5.0.6 on 2024-05-27 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0012_alter_post_time_reading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time_reading',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
