# Generated by Django 5.0.6 on 2024-05-27 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0014_alter_post_contentimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='CoverPic/default.png', null=True, upload_to='CoverPic/'),
        ),
    ]
