# Generated by Django 5.0.6 on 2024-06-02 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(blank=True, max_length=16, null=True)),
                ('cvv', models.CharField(blank=True, max_length=3, null=True)),
                ('card_name', models.CharField(blank=True, max_length=14, null=True)),
                ('expiry_date', models.DateField(blank=True, max_length=5, null=True)),
                ('month_paid', models.BooleanField(default=False)),
                ('week_paid', models.BooleanField(default=False)),
                ('free_trial', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
