# Generated by Django 5.0.6 on 2024-07-15 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpayment',
            name='payment_method_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
