# Generated by Django 5.0.6 on 2024-06-05 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0002_product_userpayment_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpayment',
            name='cvv',
            field=models.CharField(blank=True, help_text='Enter the CVV/CVC code', max_length=3, null=True),
        ),
    ]
