# Generated by Django 5.0.6 on 2024-10-28 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0002_userpayment_payment_method_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpayment',
            old_name='payment_method_id',
            new_name='subscription_id',
        ),
    ]
