# Generated by Django 5.0.6 on 2024-06-05 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0003_alter_userpayment_cvv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpayment',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='Enter expiry date in MM-YY format.', max_length=5, null=True),
        ),
    ]
