# Generated by Django 5.0.6 on 2024-10-28 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0003_rename_payment_method_id_userpayment_subscription_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpayment',
            old_name='subscription_id',
            new_name='payment_method_id',
        ),
    ]
