# Generated by Django 5.0.6 on 2024-06-05 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0004_alter_userpayment_expiry_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpayment',
            name='expiry_date',
        ),
        migrations.AddField(
            model_name='userpayment',
            name='expiry_month',
            field=models.IntegerField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='userpayment',
            name='expiry_year',
            field=models.IntegerField(blank=True, max_length=2, null=True),
        ),
    ]
