# Generated by Django 5.0.6 on 2024-06-13 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0007_userpayment_stripe_checkout_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpayment',
            name='card_name',
        ),
        migrations.RemoveField(
            model_name='userpayment',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='userpayment',
            name='cvv',
        ),
        migrations.RemoveField(
            model_name='userpayment',
            name='expiry_month',
        ),
        migrations.RemoveField(
            model_name='userpayment',
            name='expiry_year',
        ),
    ]
