# Generated by Django 5.0.6 on 2024-06-17 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0009_alter_userpayment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpayment',
            name='month_paid',
        ),
        migrations.RemoveField(
            model_name='userpayment',
            name='stripe_checkout_id',
        ),
        migrations.RemoveField(
            model_name='userpayment',
            name='week_paid',
        ),
        migrations.AddField(
            model_name='userpayment',
            name='subscription_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
