# Generated by Django 5.0.6 on 2024-06-24 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0011_remove_userpayment_subscription_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpayment',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Payment.product'),
        ),
    ]
