# Generated by Django 5.0.6 on 2024-06-26 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('change_log', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='changelog',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
