# Generated by Django 5.0.6 on 2024-07-02 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
