# Generated by Django 5.0.6 on 2024-07-21 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRankings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interactive_id', models.CharField(max_length=255)),
                ('total_profit', models.DecimalField(decimal_places=2, max_digits=32)),
                ('gain', models.DecimalField(decimal_places=2, max_digits=5)),
                ('number_of_trades', models.IntegerField()),
                ('win_streak_number', models.IntegerField()),
                ('day_streak', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
