# Generated by Django 5.0.6 on 2024-07-21 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0002_rename_userrankings_userranking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTrader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interactive_id', models.CharField(max_length=255)),
                ('trader_type', models.CharField(choices=[('DAY', 'Day'), ('SWING', 'Swing'), ('LONG', 'Long')], max_length=255)),
                ('total_profit', models.DecimalField(decimal_places=2, max_digits=32)),
                ('gain', models.DecimalField(decimal_places=2, max_digits=5)),
                ('number_of_trades', models.IntegerField()),
                ('win_streak_number', models.IntegerField()),
                ('day_streak', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('symbol', models.CharField(max_length=255)),
                ('symbol_id', models.CharField(max_length=255)),
                ('share_quantity', models.IntegerField()),
                ('price_per_share', models.FloatField()),
                ('amount_paid', models.FloatField()),
                ('side', models.CharField(max_length=2)),
                ('user_trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaderboard.usertrader')),
            ],
        ),
        migrations.DeleteModel(
            name='UserRanking',
        ),
    ]
