# Generated by Django 5.0.6 on 2024-07-21 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0003_usertrader_trade_delete_userranking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='user_trader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='leaderboard.usertrader'),
        ),
        migrations.AlterField(
            model_name='usertrader',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
    ]
