# Generated by Django 5.0.6 on 2024-08-06 07:53

import Courses.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0002_remove_course_likes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Section',
            new_name='Articles',
        ),
        migrations.RemoveField(
            model_name='course',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='course',
            name='subscribed',
        ),
        migrations.RemoveField(
            model_name='course',
            name='time_to_complete',
        ),
        migrations.RemoveField(
            model_name='course',
            name='user',
        ),
        migrations.AddField(
            model_name='course',
            name='auther',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='CoursePic/'),
        ),
        migrations.RemoveField(
            model_name='course',
            name='users_completed',
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='Courses.category'),
        ),
        migrations.AddField(
            model_name='course',
            name='users_completed',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
