# Generated by Django 5.0.6 on 2024-08-06 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0004_category_slug_course_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='completed',
        ),
    ]
