# Generated by Django 5.0.6 on 2024-08-06 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0007_alter_articles_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribed_courses',
            name='liked',
            field=models.BooleanField(default=False),
        ),
    ]
