# Generated by Django 5.0.6 on 2024-08-07 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0009_remove_subscribed_courses_liked_likes_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
