# Generated by Django 5.0.6 on 2024-08-07 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0011_completedmodules'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='module',
        ),
        migrations.AddField(
            model_name='assessment',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='Courses.course'),
        ),
    ]
