# Generated by Django 5.0.6 on 2024-08-07 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0012_remove_assessment_module_assessment_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='completed',
        ),
    ]
