# Generated by Django 5.0.6 on 2024-08-12 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0020_alter_course_liked_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribed_courses',
            name='assessment_score',
            field=models.FloatField(default=0.0),
        ),
    ]
