# Generated by Django 5.0.6 on 2024-08-12 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0021_subscribed_courses_assessment_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completedmodules',
            name='module',
        ),
        migrations.RemoveField(
            model_name='completedmodules',
            name='user',
        ),
        migrations.DeleteModel(
            name='AssessmentCompleted',
        ),
        migrations.DeleteModel(
            name='CompletedModules',
        ),
    ]
