# Generated by Django 5.0.6 on 2024-08-14 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0024_alter_answers_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='assessment',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
