# Generated by Django 5.0.6 on 2024-09-18 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0026_course_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribed_courses',
            name='completed_modules_ids',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
