# Generated by Django 5.0.6 on 2024-09-19 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0027_subscribed_courses_completed_modules_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribed_courses',
            name='completed_modules_ids',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
