# Generated by Django 5.0.6 on 2024-10-31 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0030_alter_subscribed_courses_completed_modules_ids'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='auther',
            new_name='author',
        ),
    ]
