# Generated by Django 5.0.6 on 2024-10-31 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0031_rename_auther_course_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='label',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
