# Generated by Django 5.0.6 on 2024-10-31 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0032_course_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='course',
        ),
        migrations.AddField(
            model_name='questions',
            name='assessment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='assessment_question', to='Courses.assessment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answers',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_answers', to='Courses.questions'),
        ),
    ]
