# Generated by Django 5.0.6 on 2024-11-05 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0037_alter_course_liked_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='"CoursePic/Questions/'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='image',
            field=models.ImageField(blank=True, default='CoursePic/SectionPic/Default.jpg', null=True, upload_to='CoursePic/SectionPic/'),
        ),
    ]
