# Generated by Django 5.0.6 on 2024-11-05 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0038_questions_picture_alter_articles_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribed_courses',
            name='status',
            field=models.CharField(default='in progress', max_length=50),
        ),
    ]
