# Generated by Django 5.0.6 on 2024-11-06 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0039_subscribed_courses_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Expert', 'Expert'), ('Intermediate', 'Intermediate')], default=None, max_length=50),
            preserve_default=False,
        ),
    ]
