# Generated by Django 5.0.6 on 2024-11-07 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0040_course_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='"CoursePic/Answers/'),
        ),
    ]
