# Generated by Django 5.0.6 on 2024-11-11 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0042_alter_answers_question_alter_questions_assessment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Answers',
            new_name='Answer',
        ),
        migrations.RenameModel(
            old_name='Articles',
            new_name='Article',
        ),
        migrations.RenameModel(
            old_name='Questions',
            new_name='Question',
        ),
    ]
