# Generated by Django 5.0.6 on 2024-11-11 16:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0044_rename_subscribed_courses_subscribed_course'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='completed_users',
            field=models.ManyToManyField(blank=True, related_name='completed_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
