# Generated by Django 5.0.6 on 2024-06-26 14:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourseApp', '0004_course_category_course_likes_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='subscribed',
            field=models.ManyToManyField(blank=True, related_name='subscribed', to=settings.AUTH_USER_MODEL),
        ),
    ]
