# Generated by Django 5.0.6 on 2024-06-27 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourseApp', '0006_course_likes_alter_course_subscribed_delete_likes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='users_completed',
            field=models.ManyToManyField(related_name='Course', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserCompleted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_field', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
