# Generated by Django 5.0.6 on 2024-06-27 10:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourseApp', '0007_course_users_completed_usercompleted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='section',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='section',
            name='completed',
            field=models.ManyToManyField(related_name='section_completed', to=settings.AUTH_USER_MODEL),
        ),
    ]
