# Generated by Django 5.0.6 on 2024-06-27 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourseApp', '0009_remove_assessment_score_assessmentcompleted_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='is_completed',
            field=models.ManyToManyField(related_name='module', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assessmentcompleted',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_completed', to='CourseApp.assessment'),
        ),
    ]
