# Generated by Django 5.0.6 on 2024-06-27 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourseApp', '0011_rename_is_completed_module_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='completed',
        ),
        migrations.AddField(
            model_name='assessmentcompleted',
            name='module',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='completed', to='CourseApp.module'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ModuleCompleted',
        ),
    ]
