# Generated by Django 5.0.6 on 2024-06-27 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourseApp', '0012_remove_module_completed_assessmentcompleted_module_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentcompleted',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='completed', to='CourseApp.module'),
        ),
    ]
