# Generated by Django 5.0.6 on 2024-10-01 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='followed_tickers',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
