# Generated by Django 5.0.6 on 2024-05-26 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_profile_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='ProfilePic/Default.jpg', upload_to='ProfilePic/'),
        ),
    ]
