# Generated by Django 5.0.6 on 2024-06-26 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0005_emailverification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailverification',
            name='created_at',
        ),
    ]
