# Generated by Django 5.0.6 on 2024-06-26 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0006_remove_emailverification_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverification',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='emailverification',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='emailverification',
            name='password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='emailverification',
            name='password2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
