# Generated by Django 5.0.6 on 2024-06-26 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0007_emailverification_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailverification',
            name='password2',
        ),
    ]
