# Generated by Django 5.0.6 on 2024-07-07 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0008_remove_emailverification_password2'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverification',
            name='phone_number',
            field=models.IntegerField(blank=True, max_length=11, null=True),
        ),
    ]
