# Generated by Django 5.0.6 on 2024-07-07 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0009_emailverification_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
