# Generated by Django 5.0.6 on 2024-07-07 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0011_alter_emailverification_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Phone_Number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
