# Generated by Django 5.0.6 on 2025-04-06 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy', models.CharField(max_length=50)),
                ('time_frame', models.CharField(blank=True, max_length=50, null=True)),
                ('success', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('result_value', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=9)),
                ('name', models.CharField(max_length=255)),
                ('market_cap', models.FloatField()),
                ('market_capital', models.CharField(blank=True, max_length=255, null=True)),
                ('industry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticker', to='Alerts.industry')),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy', models.CharField(max_length=50)),
                ('time_frame', models.CharField(blank=True, max_length=10, null=True)),
                ('result_value', models.FloatField(blank=True, null=True)),
                ('risk_level', models.CharField(blank=True, max_length=50, null=True)),
                ('Estimated_Revenue', models.FloatField(blank=True, null=True)),
                ('Estimated_EPS', models.FloatField(blank=True, null=True)),
                ('current_IV', models.CharField(blank=True, max_length=50, null=True)),
                ('Expected_Moves', models.CharField(blank=True, max_length=50, null=True)),
                ('earning_time', models.CharField(blank=True, max_length=50, null=True)),
                ('investor_name', models.TextField(blank=True, null=True)),
                ('transaction_type', models.CharField(blank=True, max_length=50, null=True)),
                ('shares_quantity', models.IntegerField(blank=True, null=True)),
                ('ticker_price', models.FloatField(blank=True, null=True)),
                ('amount_of_investment', models.FloatField(blank=True, null=True)),
                ('transaction_date', models.DateField(blank=True, null=True)),
                ('job_title', models.CharField(blank=True, max_length=255, null=True)),
                ('filling_date', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('time', models.TimeField(auto_now_add=True, null=True)),
                ('current_price', models.FloatField(blank=True, null=True)),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert', to='Alerts.ticker')),
            ],
            options={
                'indexes': [models.Index(fields=['ticker', 'strategy', 'result_value', 'date'], name='Alerts_aler_ticker__510ab7_idx')],
                'unique_together': {('ticker', 'strategy', 'result_value')},
            },
        ),
    ]
