# Generated by Django 5.0.6 on 2024-07-15 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alerts', '0002_alerts_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerts_details',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
