# Generated by Django 5.0.6 on 2024-07-15 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alerts', '0003_alerts_details_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social_media_mentions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reddit_mentions', models.IntegerField(null=True)),
                ('twitter_mentions', models.IntegerField(null=True)),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alerts.tickers')),
            ],
        ),
    ]
