# Generated by Django 5.0.6 on 2024-07-15 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alerts', '0004_social_media_mentions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='social_media_mentions',
            old_name='reddit_mentions',
            new_name='mentions',
        ),
        migrations.RemoveField(
            model_name='social_media_mentions',
            name='twitter_mentions',
        ),
    ]
