# Generated by Django 5.0.6 on 2024-07-16 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alerts', '0006_delete_social_media_mentions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social_media_mentions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentions', models.IntegerField(null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alerts.tickers')),
            ],
        ),
    ]
