# Generated by Django 5.0.6 on 2024-07-16 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alerts', '0007_social_media_mentions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social_media_mentions',
            name='ticker',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Alerts.tickers'),
        ),
    ]
