# Generated by Django 5.0.6 on 2024-07-17 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alerts', '0008_alter_social_media_mentions_ticker'),
    ]

    operations = [
        migrations.AddField(
            model_name='social_media_mentions',
            name='message',
            field=models.TextField(default='people are talking about this SYMBOL on social media, you should check it out'),
        ),
    ]
