# Generated by Django 5.0.6 on 2024-07-17 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alerts', '0009_social_media_mentions_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerts_details',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='alerts_details',
            name='risk_level',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='alerts_details',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='Social_media_mentions',
        ),
    ]
