# Generated by Django 5.0.6 on 2024-07-18 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alerts', '0012_remove_ticker_industry_industry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticker',
            name='market_cap',
            field=models.FloatField(),
        ),
    ]
