# Generated by Django 5.0.6 on 2024-07-18 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alerts', '0013_alter_ticker_market_cap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='industry',
            name='ticker',
        ),
        migrations.AddField(
            model_name='ticker',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticker', to='Alerts.industry'),
        ),
    ]
