# Generated by Django 5.0.6 on 2024-07-18 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alerts', '0008_alter_alerts_details_risk_level_and_more'),
        ('Alerts', '0014_remove_industry_ticker_ticker_industry'),
    ]

    operations = [
    ]
