# Generated by Django 5.0.6 on 2024-07-18 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alerts', '0015_alert'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alert',
        ),
    ]
