# Generated by Django 5.0.6 on 2024-07-18 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alerts', '0015_alert'),
        ('Alerts', '0015_merge_20240718_1510'),
    ]

    operations = [
    ]
