# Generated by Django 5.0.6 on 2024-07-18 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alerts', '0015_merge_20240718_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=8)),
                ('strategy', models.CharField(max_length=50)),
                ('strategy_time', models.CharField(max_length=5)),
                ('strategy_value', models.FloatField()),
                ('risk_level', models.CharField(max_length=50, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
