# Generated by Django 5.0.6 on 2024-07-18 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alerts', '0016_merge_0015_alert_0015_merge_20240718_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='strategy_time',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='strategy_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
