# Generated by Django 5.0.6 on 2024-07-21 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alerts', '0017_alter_alert_strategy_time_alter_alert_strategy_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert_13F',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investor_name', models.CharField(max_length=100)),
                ('transaction_tybe', models.CharField(max_length=50)),
                ('num_shares', models.IntegerField()),
                ('ticker_price', models.FloatField()),
                ('amount_of_investment', models.FloatField()),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_13f_ticker', to='Alerts.ticker')),
            ],
        ),
        migrations.CreateModel(
            name='Earning_Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy', models.CharField(max_length=50)),
                ('strategy_time', models.IntegerField()),
                ('Estimated_Revenue', models.FloatField(blank=True, null=True)),
                ('Estimated_EPS', models.FloatField(blank=True, null=True)),
                ('currunt_IV', models.CharField(max_length=50)),
                ('Expected_Moves', models.CharField(max_length=50)),
                ('earning_time', models.CharField(max_length=50, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earning_alert_ticker', to='Alerts.ticker')),
            ],
        ),
    ]
