# Generated by Django 5.0.6 on 2024-07-21 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alerts', '0018_alert_13f_earning_alert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earning_alert',
            name='Expected_Moves',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='earning_alert',
            name='currunt_IV',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
