# Generated by Django 5.0.6 on 2024-07-21 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alerts', '0019_alter_earning_alert_expected_moves_and_more'),
        ('Alerts', '0019_ticker_market_capital'),
    ]

    operations = [
    ]
