# Generated by Django 5.0.6 on 2024-07-22 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alerts', '0023_delete_percentageofrsi_alter_result_success_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert_InsiderBuyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField()),
                ('transaction_type', models.CharField(max_length=15)),
                ('buyer_name', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=255)),
                ('share_quantity', models.IntegerField()),
                ('price_per_share', models.FloatField()),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Insiderbuyers', to='Alerts.ticker')),
            ],
        ),
    ]
