# Generated by Django 5.0.6 on 2024-07-23 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alerts', '0025_alert_insiderbuyer_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert_insiderbuyer',
            name='filling_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
