# Generated by Django 5.0.6 on 2024-07-23 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alerts', '0026_alert_insiderbuyer_filling_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alert',
        ),
    ]
