# Generated by Django 5.0.6 on 2024-07-23 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alerts', '0027_delete_alert'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy', models.CharField(max_length=50)),
                ('time_frame', models.CharField(blank=True, max_length=10, null=True)),
                ('result_value', models.FloatField(blank=True, null=True)),
                ('risk_level', models.CharField(max_length=50, null=True)),
                ('Estimated_Revenue', models.FloatField(blank=True, null=True)),
                ('Estimated_EPS', models.FloatField(blank=True, null=True)),
                ('current_IV', models.CharField(blank=True, max_length=50, null=True)),
                ('Expected_Moves', models.CharField(blank=True, max_length=50, null=True)),
                ('earning_time', models.CharField(max_length=50, null=True)),
                ('investor_name', models.CharField(max_length=100)),
                ('transaction_type', models.CharField(max_length=50)),
                ('shares_quantity', models.IntegerField()),
                ('ticker_price', models.FloatField()),
                ('amount_of_investment', models.FloatField()),
                ('transaction_date', models.DateField()),
                ('job_title', models.CharField(blank=True, max_length=255, null=True)),
                ('filling_date', models.CharField(blank=True, max_length=255, null=True)),
                ('time_posted', models.DateTimeField(auto_now_add=True, null=True,blank=True)),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert', to='Alerts.ticker')),
            ],
        ),
    ]
