# Generated by Django 5.0.6 on 2024-07-23 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alerts', '0028_alert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='amount_of_investment',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='earning_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='investor_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='risk_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='shares_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='ticker_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='transaction_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='transaction_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
