# Generated by Django 5.0.6 on 2024-07-30 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alerts', '0031_alter_result_result_value_alter_result_success_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert_13f',
            name='ticker',
        ),
        migrations.RemoveField(
            model_name='alert_insiderbuyer',
            name='ticker',
        ),
        migrations.DeleteModel(
            name='Alerts_Details',
        ),
        migrations.RemoveField(
            model_name='earning_alert',
            name='ticker',
        ),
        migrations.RemoveField(
            model_name='ema_alert',
            name='ticker',
        ),
        migrations.RemoveField(
            model_name='rsi_alert',
            name='ticker',
        ),
        migrations.DeleteModel(
            name='Tickers',
        ),
        migrations.DeleteModel(
            name='Alert_13F',
        ),
        migrations.DeleteModel(
            name='Alert_InsiderBuyer',
        ),
        migrations.DeleteModel(
            name='Earning_Alert',
        ),
        migrations.DeleteModel(
            name='EMA_Alert',
        ),
        migrations.DeleteModel(
            name='Rsi_Alert',
        ),
    ]
