# Generated by Django 5.0.6 on 2024-08-04 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alerts', '0032_remove_alert_13f_ticker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='currunt_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
