# Generated by Django 5.0.6 on 2024-08-19 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alerts', '0033_alert_currunt_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert',
            old_name='currunt_price',
            new_name='current_price',
        ),
    ]
