# Generated by Django 5.0.6 on 2024-08-27 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alerts', '0035_alter_result_time_frame'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='alert',
            unique_together={('ticker', 'strategy', 'result_value', 'time_posted')},
        ),
    ]
