# Generated by Django 5.0.6 on 2024-11-11 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='date',
        ),
    ]
